sudo: false
language: python
branches:
  only:
  - master
before_script:
- pip install -r requirements.txt
script:
- sphinx-build -b html . build
- sh deploy.sh
env:
  global:
    secure: o+Q07OFlogLfEZPF8LtRsZ6TA3fAncwbfvjHzduSM5knsZejZ1x9WNONjxljKy+U8YouEMYUvQ19VPkJNXXfGca4h1Qel9PRAIEbuwToxFBs0bPBMdYgY5JKI9+H+x5wfNhhVvSfBSDCvGfQLttcpjgSCrQc4xOBd5SlWmhHUn0yDELJZ7RVhR9QdxnnSEC++u0xQffLesTkN+LuJ8LKIH1h1LYiWAxHeIBGULIf/2R5LWRReQLCN7qixx5ASR/sUCk/jnET22EjaS+qWWMM5cHgtr3SBYVy5o0p1h2G0cImJOWdAGNnU0N/naYmjDDJTSbphB0TB4zbEAcKiinshU+qiWLiuMMbgIeHEksFoQcZIQD3Y8u7mv31vUVsW79fKeKKFBQLOF/Qa6vbI+UfCE833CWVXpk3h84ZPlzyyxpdZBJPtJxVgMlvH9TUBN4IB03Hf1Fjjv+O9ON3p0HvQfogxwQ6F4hiiiyqlFH25k2Ho44XjlOQglX8IbNE8lWy0yDqk7I2foQNYLOUNoXJaABjBhc6uRwvPBS5V3CYKUC5q93QYS2NolJ+M0ukmDYbcVpx44S3nyENXedHxbYvAuAMXTZTROt9ZujZvgJYz/IApU5g7S4QpSjhLBjyGeKrvPre3ms+/OsPcw1pSNbIl6J1oPrTJZK741aIYoiuQoY=
